# Generated by Django 3.0.6 on 2020-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='img/dishes', verbose_name='Фото блюда')),
                ('text', models.TextField(verbose_name='Описание блюда')),
                ('price', models.CharField(default='NULL', max_length=200, verbose_name='Стоимость( Указываем только цифру)')),
                ('weight', models.CharField(default='NULL', max_length=200, verbose_name='Вес( Указываем только цифру)')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок сайта')),
                ('background', models.ImageField(upload_to='img/dishes', verbose_name='Фоновое изображение сайта')),
                ('top_pic', models.ImageField(upload_to='img/dishes', verbose_name='Фоновое изображение кнопки АКЦИЯ')),
            ],
            options={
                'verbose_name': 'Элементы страницы',
                'verbose_name_plural': 'Элементы страницы',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название раздела меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
