# Generated by Django 3.0.6 on 2020-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200530_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='img/dishes', verbose_name='Фото блюда')),
                ('text', models.TextField(verbose_name='Описание блюда')),
                ('price', models.CharField(default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)')),
                ('weight', models.CharField(default='0', max_length=200, verbose_name='Вес( Указываем только цифру)')),
            ],
            options={
                'verbose_name': 'Блюдо страницы 2',
                'verbose_name_plural': 'Блюда страницы 2',
            },
        ),
        migrations.CreateModel(
            name='Dishes3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='img/dishes', verbose_name='Фото блюда')),
                ('text', models.TextField(verbose_name='Описание блюда')),
                ('price', models.CharField(default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)')),
                ('weight', models.CharField(default='0', max_length=200, verbose_name='Вес( Указываем только цифру)')),
            ],
            options={
                'verbose_name': 'Блюдо страницы 3',
                'verbose_name_plural': 'Блюда страницы 3',
            },
        ),
        migrations.AlterModelOptions(
            name='dishes1',
            options={'verbose_name': 'Блюдо страницы 1', 'verbose_name_plural': 'Блюда страницы 1'},
        ),
    ]
