# Generated by Django 3.0.6 on 2020-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemHorizont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название раздела горизонтального меню')),
            ],
            options={
                'verbose_name': 'Пункт горизонтального меню',
                'verbose_name_plural': 'Пункты горизонтального меню',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт вертикального меню', 'verbose_name_plural': 'Пункты вертикального меню'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название раздела вертикального меню'),
        ),
    ]
