# Generated by Django 3.0.6 on 2020-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200601_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='img/dishes', verbose_name='Фото блюда')),
                ('text', models.TextField(verbose_name='Описание блюда')),
                ('price', models.CharField(default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)')),
                ('weight', models.CharField(default='0', max_length=200, verbose_name='Вес( Указываем только цифру)')),
            ],
            options={
                'verbose_name': 'Блюдо страницы 4',
                'verbose_name_plural': 'Блюда страницы 4',
            },
        ),
        migrations.AlterModelOptions(
            name='top',
            options={'verbose_name': 'Блюдо страницы АКЦИИ', 'verbose_name_plural': 'Блюда страницы АКЦИИ'},
        ),
    ]
