# Generated by Django 3.0.6 on 2020-06-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_dishes100_dishes101_dishes102_dishes103_dishes5_dishes6_dishes7_dishes8'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'Блюдо страницы АКЦИИ', 'verbose_name_plural': 'Блюда страницы АКЦИИ'},
        ),
    ]
