# Generated by Django 3.0.6 on 2020-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200601_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItemHorizont',
        ),
        migrations.AlterModelOptions(
            name='dishes1',
            options={'verbose_name': 'Блюдо страницы (Холодные закуски)', 'verbose_name_plural': 'Блюда страницы (Холодные закуски)'},
        ),
        migrations.AlterModelOptions(
            name='dishes2',
            options={'verbose_name': 'Блюдо страницы (Салаты)', 'verbose_name_plural': 'Блюда страницы (Салаты)'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes1',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes1',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes1',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes100',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes100',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes100',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes101',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes101',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes101',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes102',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes102',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes102',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes103',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes103',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes103',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes2',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes2',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes2',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes3',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes3',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes3',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes4',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes4',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes4',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes5',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes5',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes5',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes6',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes6',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes6',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes7',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes7',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes7',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes8',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Стоимость( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='dishes8',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dishes8',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='Вес( Указываем только цифру)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название раздела меню'),
        ),
    ]
