# Generated by Django 3.0.6 on 2020-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200608_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='backgroundMain',
            field=models.ImageField(default='', upload_to='img/dishes', verbose_name='Фоновое изображение стартовой страницы сайта'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='', upload_to='img/dishes', verbose_name='Фоновое изображение раздела меню'),
        ),
    ]
